- .gitignore
- src/config.ts
- src/index.ts
- src/lib/deployment.ts
- src/lib/language.ts
- src/lib/package.ts
- src/lib/plan.ts
- src/lib/protocol.ts
- src/startup.ts
- src/utils.ts
- Added Docs. to Each Required File. ( docs. suggested by @viferga )
- Plans Added
fixes #9
> Implemented deployment in case of `PackageError.None` in `index.ts` & Added Docs.

- package-lock.json
- src/index.ts
- src/utils.ts
Remove ignore files. Use the files from packageDescriptor to zip and generate the archive
> Refactor the zip utility

- package-lock.json
- src/auth.ts
- src/index.ts
- src/test/integration.protocol.spec.ts
With this pull request, login functionality will start working in the deploy cli tool.
Quick Video Demonstration -> https://asciinema.org/a/09ErT1kixgrijbJBWiKMowsXk?speed=2
1) If you are currently in your project folder which you wanna deploy, type
```js
$ metacall-deploy
```
2) With a different name for your project
```js
$ metacall-deploy --projectName=differentName
```
3) If you are in some other directory and still wanna deploy a project which is at some other path,
```js
$ metacall-deploy --workdir=absolutePathToTheProject
```
> feat: added cli login.

- src/index.ts
Video demonstration - https://asciinema.org/a/LPNhsQaT5OUX9TUcZ8z5s4cxP
**Description**
Added help command.
**Context**
Printing CLI guide needs to be updated more than this, but for now it's OK to make it work.
> feat : added help command

- package-lock.json
- src/auth.ts
- src/cli/args.ts
- src/index.ts
It was getting hard to read the index.ts file because of more than 100 lines of code of CLI args, hence moved.
> refactored cli args

- package-lock.json
- package.json
- src/cli/inspect.ts
- src/config.ts
- src/index.ts
- src/utils.ts
With this pull request, you can look at all of your deployments on FAAS.
1) Open your terminal & hit the command given below:-
```js
$ metacall-deploy  --inspect
```
> [WIP] feat: added flag (--inspect)

- src/cli/messages.ts
- src/cli/progress.ts
- src/index.ts
- src/utils.ts
1. Fixed issue #32 
2. Added apiError
3. Removed Todo comment as requested
4. Resolved Conflict in index.ts
> bug: hide gauge progress after completing and added apiError format

- package-lock.json
- src/cli/logs.ts
- src/cli/selection.ts
- src/index.ts
Pending:-
1) For now user can only look at one type of log at a time, we need to implement TUI to show all the types of logs to the user.
> feat: implemented logs

- package-lock.json
- src/index.ts
implemented all delete logic inside try catch
> ref : refactor delete logic.

- src/deploy.ts
- src/index.ts
Same as the PR's title.
Will be showing logs of deployment once the [#10](https://github.com/metacall/protocol/pull/10) and [#8](https://github.com/metacall/protocol/pull/10) gets merged in the protocol.
> ref: Refactored and type checked of URL in --addrepo flag

- package-lock.json
- package.json
- src/auth.ts
- src/cli/messages.ts
- src/delete.ts
- src/deploy.ts
- src/logs.ts
Fixes #49 
We were using ```axios``` only because of ```AxiosError```, so this pr includes removal of ```axios``` package.
> feat: removed axios as a package

- package-lock.json
- package.json
- src/cli/args.ts
Fixes #45 
This pr solves the issue mentioned above.
Used this wiki page to fix this issue - https://github.com/75lb/command-line-args/wiki/Mocha-test-script-example
> bug: UNKNOWN_OPTION exception bug resolved

- src/test/cli.integration.spec.ts
- src/test/cmd.ts
- src/test/protocol.integration.spec.ts
- src/test/resources/integration/time-app-web/.gitignore
- src/test/resources/integration/time-app-web/README.md
- src/test/resources/integration/time-app-web/index.html
- src/test/resources/integration/time-app-web/index.py
- src/test/resources/integration/time-app-web/metacall-py.json
- src/test/resources/integration/time-app-web/sat.txt
Added cli-integration-test for commands such as :-
> tests: cli-integration-tests

- src/cli/inspect.ts
- src/config.ts
- src/delete.ts
- src/index.ts
- src/logs.ts
- src/startup.ts
- src/test/cmd.ts
- src/test/protocol.integration.spec.ts
> feat: args confDir

- src/cli/args.ts
- src/index.ts
Adding BaseURl to args file then call it in index.ts
> Base URL Task

- src/cli/selection.ts
- src/index.ts
Fixes #67 
Testing is not done yet for this change.
> Fixed auth and plan selection order.

- package-lock.json
- src/index.ts
> listed plans properly

- src/delete.ts
- src/force.ts
- src/index.ts
- src/plan.ts
> feat: added force flag

- githooks/pre-push-update-version
This PR updates the hook to make it work correctly for the second instance inside the lockfile.
> Fix version hook

- githooks/pre-push-update-version
Signed-off-by: Param Siddharth <contact@paramsid.com>
> Move tag up with new version-update commit

- package-lock.json
- package.json
> Revert "Updating version to v0.1.7"

- package-lock.json
- package.json
- src/cli/args.ts
- src/cli/unknown.ts
- src/help.ts
- src/index.ts
> Partial parsing

- src/cli/validateToken.ts
- src/index.ts
> expired token will automatically get refreshed

- package-lock.json
- src/index.ts
Top level error handling for expired tokens, will remove many number of try catch block in future pr's
> handled jwt token errors

- src/cli/inspect.ts
--inspect command was fetching extra unnecessary packages, so this is a fix of it.
> Fix: inspect command

- src/test/cli.integration.spec.ts
> added test for env variables
